[package]
name = "archyrt_core"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
image = "0.23.14"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "core_benchmark"
harness = false