openapi: 3.0.1
info:
  title: Archytex
  description: API used for the Archytex project.
  contact:
    email: texyfore@gmail.com
  version: 0.1.0b
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: http://localhost:8080/api
tags:
  - name: authentication
    description: APIs regarding login and registration
  - name: assets
    description: Endpoint to access public files and metadata
  - name: authenticated
    description: Endpoints requiring authentication
  - name: projects
    description: Project management
paths:
  /register:
    post:
      summary: Create a new account
      tags:
        - authentication
      responses:
        '400':
          description: User already exists
        '403':
          description: Invalid captcha
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                email:
                  type: string
                password:
                  type: string
                captcha:
                  type: string
  /verify:
    get:
      summary: Verifies a registered account
      tags:
        - authentication
      responses:
        '400':
          description: Invalid token
      parameters:
        - name: token
          in: query
          description: Token from verification E-Mail
          schema:
            type: string
          required: true
  /login:
    post:
      summary: Logs into an account
      tags:
        - authentication
      responses:
        '200':
          description: Successful login
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid username or password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
  /ws:
    summary: WebSocket for Project updated
    description: This endpoint is undocumented due to documentation software limitations
  /assets:
    get:
      summary: Get list of props and textures
      tags:
        - assets
      responses:
        '200':
          description: List of all assets
          content:
            application/json:
              schema:
                type: object
                properties:
                  props:
                    $ref: '#/components/schemas/Asset'
                  textures:
                    $ref: '#/components/schemas/Asset'
  /render/{render}:
    get:
      summary: Gets the image of a render
      tags:
        - assets
        - projects
      responses:
        '200':
          description: Rendered image
          content:
            image/png:
              schema:
                type: string
                format: binary
        '400':
          description: Invalid request
      parameters:
        - name: render
          in: path
          required: true
          schema:
            type: string
  /auth/user:
    post:
      summary: Gets information about the currently logged in user
      tags:
        - authenticated
      responses:
        '200':
          description: Short-form user information
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  email:
                    type: string
                  coins:
                    type: number
        '400':
          description: Missing Bearer token
        '401':
          description: Unauthorized
      security:
        - api_key: []
  /project:
    post:
      summary: Creates new project
      tags:
        - authenticated
        - projects
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully created project
        '400':
          description: JSON formatting error
        '401':
          description: Unauthorized
  /project/{id}:
    delete:
      summary: Delete project
      tags:
        - authenticated
        - projects
      parameters:
        - name: id
          in: path
          schema:
            type: string
          required: true
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully deleted project
        '400':
          description: Invalid ID
        '401':
          description: Unauthorized
    patch:
      summary: Rename project
      tags:
        - authenticated
        - projects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully deleted project
        '400':
          description: Invalid ID
        '401':
          description: Unauthorized
      requestBody:
        description: New name
        content:
          application/json:
            schema:
              type: string
  /project/{id}/data:
    post:
      summary: Uploads new project file
      tags:
        - authenticated
        - projects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully saved project
        '401':
          description: Unauthorized
        '404':
          description: Project not found
      requestBody:
        description: Project file in the proprietary Archytex scene format
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
    get:
      summary: Downloads latest project file
      tags:
        - authenticated
        - projects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully fetched project file
          content:
            application/octet-stream:
              schema:
                type: string
                format: binary
        '401':
          description: Unauthorized
        '404':
          description: Project not found
  /project/{id}/render:
    post:
      summary: Sends project to render queue
      tags:
        - authenticated
        - projects
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      security:
        - api_key: []
      responses:
        '200':
          description: Successfully saved project
        '400':
          description: Invalid parameter
        '404':
          description: Project not found
      requestBody:
        description: Project file in the proprietary Archytex scene format
        content:
          application/octet-stream:
            schema:
              type: string
              format: binary
components:
  securitySchemes:
    api_key:
      type: http
      scheme: bearer
  schemas:
    User:
      type: object
      properties:
        id:
          type: string
        username:
          type: string
        email:
          type: string
        coins:
          type: number
        projects:
          type: array
          items:
            $ref: '#/components/schemas/Project'
    Project:
      type: object
      properties:
        id:
          type: string
        title:
          type: string
        created:
          type: string
        path:
          type: string
        renders:
          type: array
          items:
            $ref: '#/components/schemas/Render'
    Render:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        status:
          type: number
        started:
          type: string
        finished:
          type: string
        icon:
          type: string
    Asset:
      type: object
      properties:
        _id:
          type: string
        id:
          type: number
        url:
          type: string
        public:
          type: boolean
