[package]
name = "kleng"
version = "1.0.0"
edition = "2021"

[dependencies]
clap = "3"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
image = "0"
gltf = "1"
asset = { path = "../editor/packages/asset" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"