[package]
name = "amdl"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "=1.0.30"
bincode = "=1.3.3"
serde = { version = "=1.0.133", features = ["derive"] }
mesh = { path = "../mesh", features = ["serialize"] }
asset-id = { path = "../asset-id", features = ["serde"] }