FROM golang:alpine AS build

ADD backend /archytex/backend
WORKDIR /archytex/backend
RUN go build main.go


FROM alpine

COPY --from=build /archytex/backend/main /archytex/backend
COPY --from=build /archytex/backend/templates /archytex/templates
WORKDIR /archytex
ENTRYPOINT [ "/archytex/backend" ]