FROM rust:alpine AS build

ADD raytracer/archyrt-core /archytex/archyrt/archyrt-core
ADD raytracer/archyrt-dom /archytex/archyrt/archyrt-dom
ADD editor /archytex/editor

WORKDIR /archytex/archyrt/archyrt-dom
RUN cargo build --release

FROM alpine
COPY --from=build /archytex/archyrt/archyrt-dom/target/release/archyrt_dom /archytex/raytracer/archyrt_dom
WORKDIR /archytex/raytracer
ENTRYPOINT [ "/archytex/raytracer/archyrt_dom" ]