[package]
name = "mesh"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = "=0.18.0"
serde = { version = "1.0.133", features = ["derive"], optional=true }
bytemuck = { version="=1.7.3", features = ["derive"], optional=true }