[package]
name = "formats"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "=1.0.30"
bincode = "=1.3.3"
cgmath = { version = "=0.18.0", features = ["serde"] }
serde = { version = "=1.0.133", features = ["derive"] }
asset-id = { path = "../asset-id", features = ["serde"] }