[package]
name = "web-runner"
version = "1.0.0"
edition = "2021"
description = "The Archytex editor's web runner"
authors = ["Gulyás Arnold"]

[lib]
crate-type = ["cdylib", "rlib"]

[profile.releaase]
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
winit = "0"
app = { path = "../app" }
wasm-bindgen = "0"
console_error_panic_hook = "0"
js-sys = "0"
web-sys = { version = "0", features = ["Document", "Window", "Node"] }