[package]
name = "web-runner"
version = "0.1.0"
edition = "2021"
description = "The Archytex editor's web runner"
authors = ["Gulyás Arnold"]

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
winit = "0"
app = { path = "../app" }
wasm-bindgen = "0"
web-sys = "0"