[package]
name = "web-runner"
version = "0.1.0"
edition = "2021"

[lib]
crate_type = ["cdylib", "rlib"]

[dependencies]
console_error_panic_hook = "0.1.7"
wasm-bindgen = "=0.2.78"
js-sys = "=0.3.55"
viewport = { path = "../../viewport" }