[package]
name = "archyrt_dev"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
archyrt_core = {path="../archyrt-core"}
image = "0.23.14"