[package]
name = "agzm"
version = "0.1.0"
edition = "2021"

[dependencies]
thiserror = "=1.0.30"
bincode = "=1.3.3"
gizmo = { path = "../gizmo", features = ["serialize"] }
serde = { version = "=1.0.133", features = ["derive"] }